### ISSUE TITLE
Make the "login with your XXXX account" link a big, nice looking button instead

### ISSUE THREAD

**Issue by bjornmeansbear** [cape-io/cape-editor#19]
https://www.dropbox.com/s/3xjoi321e0522vx/Screenshot%202015-12-02%2019.52.00.png?dl=0

I think a button or something more obvious would make it much more clear what the next desired step is.

**Comment by webmasterkai** [comment]
Using the google login image for now.
![Google Login](https://developers.google.com/identity/images/btn_google_signin_dark_normal_web.png)
