### ISSUE TITLE
Submit/Save does not appear to be save the images I upload in MICA profile

### ISSUE THREAD

**Issue by bjornmeansbear** [cape-io/cape-editor#32]
Submit button is working in CAPE profile, but doesn't seem to submit/save in the MICA profile. Each time I add images and then come back, the images themselves don't appear to be there? New images I tried to add aren't saved.

Clicking submit before took you back to the mixer screen. It still does that on the CAPE profile, but doesn't appear to do anything on the MICA profile.

**Comment by webmasterkai** [comment]
Might it be that you click submit before the images finish uploading? I need to make sure I correctly validate that the image uploaded correctly before allowing submit! oofta

**Comment by bjornmeansbear** [comment]
That isn't the problem in my case.

**Comment by bjornmeansbear** [comment]
Okay, I see the image thumbnails now, so that is an improvement, but I am still unable to "submit" any changes — including removing artwork.

**Comment by webmasterkai** [comment]
Is it possible you don't have a title on the artwork? It wasn't saving for me and then I noticed title was required. I'll look into why the error isn't showing up.

**Comment by bjornmeansbear** [comment]
seems to be resolved.
