### ISSUE TITLE
Rip out redux-form

### ISSUE THREAD

**Issue by webmasterkai** [cape-io/cape-editor#38]
It doesn't work in ways we need.

**Comment by bjornmeansbear** [comment]
is that was is ~~powering~~ building/generating/rendering all the forms? or is that just a small piece?

**Comment by webmasterkai** [comment]
It's a tool that is part of how the content types are working. We really need to go back to the individual field concept for the kinds of things we are trying to do.

**Comment by bjornmeansbear** [comment]
Oh interesting. Okay. Everything becomes a single entity that is included or not in an object or subject?

**Comment by webmasterkai** [comment]
Field objects get attached to subjects. A field obj might be a single value or an object of values. I want more of a free form field selection based on subject type rather than the "content type" idea.

**Comment by bjornmeansbear** [comment]
Right. So a person is a subject — so they have objects like name, artworks, etc.

Is an artwork on its own a subject with its own name object, etc. then?

MICA Grad show is a subject, and it is a collection of other subjects – the people... and then are there still "objects" like name, etc. that are assignable to MGS... whew.

**Comment by webmasterkai** [comment]
replaced with redux-field
