### ISSUE TITLE
Totally unclear that the "NAME" tab up at the top is something that should be edited by user

### ISSUE THREAD

**Issue by bjornmeansbear** [cape-io/cape-editor#44]
Does that become the main way the "user" is identified? should it auto complete with their email or be an ID# or something? Or is there someway to get them to fill it in and that auto fills the first/last names of their longer name option?

**Comment by webmasterkai** [comment]
https://schema.org/name

The suggestion is to use https://schema.org/givenName https://schema.org/familyName instead.

However, there is a concept of "Display Name" or "Label" that is the `name` field on every `Thing`. I think it's worth removing or making a clear description that it can be used as a Display Name. Some API sources have the full name combined into one text field like `fullName` and I was wanting a place to display that information. Perhaps we only show it when we have that information from somewhere.

**Comment by bjornmeansbear** [comment]
My comment isn't about the validity of the schema, it just isn't clear that the user should fill that in, do we want the user to be in control of that, or do we name them...

It's strange to have to enter your name twice — I guess its sort of like their user name though? does it need to be unique?

**Comment by webmasterkai** [comment]
You could think of it as the `title` field on a Drupal node. I'll just remove it for now. It's not a username or a unique thing. It's just where I store a full name as one text field in the backend if we get that information from somewhere.

**Comment by bjornmeansbear** [comment]
Yeah that makes sense. I don't think you need to hide it, I just am wondering if we want the users to name themselves and whether or not it needs to be unique — it sounds like it doesn't need to be so its okay to let users fill it in. The design can make it clear that its editable
