### ISSUE TITLE
Useful fields to add

### ISSUE THREAD

**Issue by bjornmeansbear** [cape-io/cape-editor#45]
- [ ] Organization (affiliation? memberOf? worksFor? « any of these? all of these?)
- [x] description (there is a description property at schema.org)
- [x] address (and to be able to add multiple addresses — billing, shipping, etc.)

TBD...

**Comment by webmasterkai** [comment]
- [x]  WebSite
- [ ] CreativeWork

Description is easy because it's a simple text field. PostalAddress is a little more involved because it's creating a new entity and then linking it to the person. Similar to ImageObject and Oranization.

**Comment by bjornmeansbear** [comment]
Good to know.
Address can be later. Even just organization allows it to start working in the way we're thinking... so those others can be To Come still...

**Comment by webmasterkai** [comment]
Closing in favor of #46 and #48.

**Comment by bjornmeansbear** [comment]
good call. Thanks.
